### ISSUE TITLE
Need assistant on how to use plugin

### ISSUE THREAD

**Issue by franciscoiarussi** [JeffJankowski/postgraphile-plugin-json-patch#1]
Hi! I can't make it work, here is an example of the table that i have on my DB

CREATE  TABLE "public"."prueba" (
                                  "prueba_id"            uuid DEFAULT gen_random_uuid() NOT NULL  ,
                                  "metadata"        json    ,
                                  "title"    varchar  ,
                                  CONSTRAINT "prueba_pkey" PRIMARY KEY ( "prueba_id" )
);

and i want to use this plugin to the **metadata** field, so every time i update that field it doesn't override all json but only the fields specified on the mutation. Can someone help me? Thanks!

**Comment by JeffJankowski** [comment]
You may have a misunderstanding of what this plugin was created to achieve, or I may not fully understand your use-case. So what `postgraphile-plugin-json-patch` does is essentially replace the type of a parameter in a pg function in the generated graphql schema with a strongly-typed representation that is already created by Postgraphile.

The motivation was that I needed the patch functionality that Postgraphile provides out-of-the-box (similar to what you're looking for where only some fields are written out to a table), but in custom functions/mutations. To achieve this, I create pg functions that accept the JSON type and then use this plugin to override that type with a Postgraphile patch type. This provides an easier development experience for graphql consumers as well as a strong contract vs an opaque JSON type.

All the JSON manipulation still needs to be manually written in a pg function; which is sounds like you need to do. Therefore, I'm not sure if this plugin will be much use to you.

**However, it _sounds_ like you're accepting JSON in a mutation and also storing that as JSON, and thus just need to merge two JSON objects. This could be as simple as updating a row with `json1 || json2` in a postgres function depending on the mutation payload.**

**Comment by franciscoiarussi** [comment]
Thank you for the response Jeff!
